# Generated by Django 4.1.2 on 2022-10-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=80)),
                ('Histidine', models.FloatField()),
                ('Isoleucine', models.FloatField()),
                ('Leucine', models.FloatField()),
                ('Lysine', models.FloatField()),
                ('Methionine', models.FloatField()),
                ('Phenylalanine', models.FloatField()),
                ('Threonine', models.FloatField()),
                ('Tryptophan', models.FloatField()),
                ('Valine', models.FloatField()),
                ('Tyrosine', models.FloatField()),
                ('category_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=80)),
            ],
        ),
    ]
