# Generated by Django 4.1.2 on 2022-10-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category_id',
            field=models.IntegerField(),
        ),
    ]
