# Generated by Django 4.1.2 on 2022-10-26 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0002_alter_food_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amino_json_responder.foodcategory'),
        ),
    ]
