# Generated by Django 4.1.2 on 2022-10-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0003_alter_food_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='category_id',
            new_name='category',
        ),
    ]
