# Generated by Django 4.1.2 on 2022-10-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0006_rename_food_category_food_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='category',
            new_name='food_category',
        ),
    ]
