# Generated by Django 4.1.2 on 2022-10-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0007_rename_category_food_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
