# Generated by Django 4.1.2 on 2022-10-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0009_remove_foodcategory_vegan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
