# Generated by Django 4.1.2 on 2022-11-18 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0012_food_food_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='id',
        ),
        migrations.AlterField(
            model_name='food',
            name='Histidine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='amino_json_responder.nutrient'),
        ),
    ]
