# Generated by Django 4.1.2 on 2022-11-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0014_nutrientcategory_nutrient_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrientcategory',
            name='unit',
            field=models.CharField(default='g', max_length=10),
            preserve_default=False,
        ),
    ]
