# Generated by Django 4.1.2 on 2022-11-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0015_nutrientcategory_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='food',
            name='Histidine',
        ),
        migrations.AddField(
            model_name='food',
            name='Histidine',
            field=models.ManyToManyField(to='amino_json_responder.nutrient'),
        ),
    ]
