# Generated by Django 4.1.2 on 2022-11-18 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0017_alter_food_histidine_remove_food_isoleucine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='Histidine',
        ),
        migrations.RemoveField(
            model_name='food',
            name='Isoleucine',
        ),
        migrations.AddField(
            model_name='food',
            name='Histidine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_requests_created', to='amino_json_responder.nutrient'),
        ),
        migrations.AddField(
            model_name='food',
            name='Isoleucine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reques', to='amino_json_responder.nutrient'),
        ),
    ]
