# Generated by Django 4.1.2 on 2022-11-18 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0018_remove_food_histidine_remove_food_isoleucine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Histidine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_string_after_histidine', to='amino_json_responder.nutrient'),
        ),
        migrations.AlterField(
            model_name='food',
            name='Isoleucine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_string_after_isoleucine', to='amino_json_responder.nutrient'),
        ),
    ]
