# Generated by Django 4.1.2 on 2022-11-18 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0020_alter_food_histidine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Isoleucine',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_string_after_isoleucine', to='amino_json_responder.nutrient'),
        ),
    ]
