# Generated by Django 4.1.2 on 2022-11-18 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0021_alter_food_isoleucine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Histidine',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histidine', to='amino_json_responder.nutrient'),
        ),
        migrations.AlterField(
            model_name='food',
            name='Isoleucine',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isoleucine', to='amino_json_responder.nutrient'),
        ),
    ]
