# Generated by Django 4.1.2 on 2022-11-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0022_alter_food_histidine_alter_food_isoleucine'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='CystEine',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='Histidine',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='Isoleucine',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Nutrient',
        ),
        migrations.DeleteModel(
            name='NutrientCategory',
        ),
    ]
