# Generated by Django 4.1.2 on 2022-11-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0023_food_cysteine_alter_food_histidine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='TotalCarbohydrates',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='TotalEnergy',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='TotalFat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='TotalProteine',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
