# Generated by Django 4.1.2 on 2022-11-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0025_food_istruecysteine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Histidine',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='IsTrueCysteine',
            field=models.BooleanField(default=False),
        ),
    ]
