# Generated by Django 4.1.2 on 2022-11-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0026_alter_food_histidine_alter_food_istruecysteine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='CystEine',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='Isoleucine',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='Leucine',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='Lysine',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='Methionine',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='Phenylalanine',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='Threonine',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='TotalCarbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='TotalEnergy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='TotalFat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='TotalProteine',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='Tryptophan',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='Tyrosine',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='Valine',
            field=models.FloatField(default=0),
        ),
    ]
