# Generated by Django 4.1.2 on 2022-11-19 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0027_alter_food_cysteine_alter_food_isoleucine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='TotalProteine',
            new_name='TotalProtein',
        ),
    ]
