# Generated by Django 4.1.2 on 2022-11-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0028_rename_totalproteine_food_totalprotein'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='TotalProtein',
            new_name='TotalProteine',
        ),
    ]
