# Generated by Django 4.1.2 on 2022-11-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0029_rename_totalprotein_food_totalproteine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='TotalProteine',
            new_name='TotalProtein',
        ),
    ]
