# Generated by Django 4.1.2 on 2022-11-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0030_rename_totalproteine_food_totalprotein'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fdc_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
