# Generated by Django 4.1.2 on 2022-11-24 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0031_food_fdc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplementaryPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_1_fdc_id', models.IntegerField(default=0)),
                ('food_2_fdc_id', models.IntegerField(default=0)),
                ('AminoScore', models.FloatField(default=0)),
                ('food_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_1', to='amino_json_responder.foodcategory')),
                ('food_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_2', to='amino_json_responder.foodcategory')),
            ],
        ),
    ]
