# Generated by Django 4.1.2 on 2022-11-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0032_complementarypair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='fdc_id',
            field=models.IntegerField(default=0),
        ),
    ]
