# Generated by Django 4.1.2 on 2022-11-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0033_alter_food_fdc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementarypair',
            name='food_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_1', to='amino_json_responder.food'),
        ),
        migrations.AlterField(
            model_name='complementarypair',
            name='food_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_2', to='amino_json_responder.food'),
        ),
    ]
