# Generated by Django 4.1.2 on 2022-11-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0034_alter_complementarypair_food_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complementarypair',
            name='food_1_part',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='complementarypair',
            name='food_2_part',
            field=models.FloatField(default=0),
        ),
    ]
