# Generated by Django 4.1.2 on 2022-12-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amino_json_responder', '0036_rename_aminoscore_complementarypair_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='AminoAcidsSum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='RelativeCystEine',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='RelativeHistidine',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='RelativeIsoleucine',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='RelativeLeucine',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='RelativeLysine',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='RelativeMethionine',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='RelativePhenylalanine',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='RelativeThreonine',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='RelativeTryptophan',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='RelativeTyrosine',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='RelativeValine',
            field=models.FloatField(default=0),
        ),
    ]
